- name: Collecting Devises from Netbox
  hosts: localhost
  vars:
    Devices: []
  tasks:
  - name: Getting devices from Netbox
    set_fact: Devices="{{ Devices + [item] }}"
    loop: "{{ query('netbox.netbox.nb_lookup', 'devices', api_endpoint='http://10.66.66.5/', token='4bdd2ebafc4c09298607a20a6c736e8fd4cac563') }}"
  - name: Store data in file
    delegate_to: 127.0.0.1
    copy:
      content:
        - "{{ Devices }}"
      dest: ~/lab3/devices.json
  - name: debug
    debug: var=Devices
